services:
  - type: web
    name: finexa-ai-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: N8N_WEBHOOK_URL
        sync: false
      - key: N8N_BASE_URL
        sync: false
      - key: PEXELS_API_KEY
        sync: false
